### ISSUE TITLE
Mauvaise couleur pour le thème de Télécom SudParis

### ISSUE THREAD

**Issue by Pedagotheque** [call-learning/moodle-theme_imtpn_telecom_sud_paris#1]
Bonjour Laurent,
Actuellement, la couleur du thème theme_imtpn_telecom_sud_paris semble être le #3c3c3c alors que ce devrait être le #225278. Pourrais-tu procéder au changement?
Te remerciant
Cordialement
__
Camille

**Comment by laurentdavid** [comment]
Je viens de corriger cela dans le thème imtpn directement car les couleurs de base sont déclarée là.
